version: '3.1'
services:
  web:
    build: ./dockerfiles/
    container_name: nkokoconnect
    platform: linux/x86_64
    depends_on:
      - db
    ports:
      - "8069:8069"
    restart: always
    volumes:
      - odoo-web-data:/var/lib/odoo
      # - ./config:/etc/odoo
      - ./extraaddons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password  
    command: --dev=reload  # Auto-reloads Python code changes          
  db:
    image: postgres:latest
    container_name: nkokoconnectdb
    platform: linux/x86_64
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"  
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8860:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: johnbolt651@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoo
    volumes:
      - pgadmin-data:/var/lib/pgadmin  
volumes:
  odoo-web-data:
  odoo-db-data:
  pgadmin-data:
secrets:
  postgresql_password:
    file: odoo_pg_pass