{
    'name': "Nkoko Connect",
    'version': '18.0.1.0.0',
    'depends': [
        'base', 
        'contacts', 
        'mail', 
        'web', 
        'stock',
        'purchase', 
        'website', 
        'sale_management',
        'im_livechat',
        'utm',
        'spreadsheet_dashboard',
    ],
    'summary': "Farm management system for farmers",
    'author': "GeoiWorks",
    'category': 'Farming',
    'description': """Farm management system for farmers""",
    'data': [
        'security/ir.model.access.csv',
        'views/farmers.xml',
        'views/hide_menus.xml',
    ],
    'assets': {
        'web.assets_frontend': [],
        'web.assets_backend': [],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'sequence': 1,
}