{
    'name': "Nkoko Connect",
    'version': '18.0.1.0.0',
    'depends': [
        'base', 
        'contacts', 
        'mail', 
        'web', 
        'stock',
        'purchase', 
        'website', 
        'sale_management',
        'im_livechat',
        'spreadsheet_dashboard',
        'auth_signup',
    ],
    'summary': "Farm management system for farmers",
    'author': "GeoiWorks",
    'category': 'Farming',
    'description': """Farm management system for farmers""",
    'data': [
        'security/user_roles.xml',
        'views/hide_menus.xml',
        'views/farmer/farmers.xml',
        'views/signup_template.xml',
        'views/farmer/farm_details.xml',
        'views/farmer/farmer_dashboard.xml',
        'views/farmer/reminders.xml',
        'data/cron.xml',
    ],
    'assets': {
        'web.assets_frontend': [],
        'web.assets_backend': [
            'nkoko_connect/static/src/js/farmer_dashboard.js',
            'nkoko_connect/static/src/xml/farmer_dashboard.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'sequence': 1,
}